version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.3
    ports:
      - "8180:8180"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - "start-dev"
      - "--http-port=8180"
      - "--spi-action-token-handler-external-app-notification-hmac-secret=aSqzP4reFgWR4j94BDT1r+81QYp/NYbY9SBwXtqV1ko="
    volumes:
      - ./providers:/opt/keycloak/providers

  wildfly:
    image: jboss/wildfly:latest
    ports:
      - "8080:8080"
    volumes:
      - ./app:/opt/jboss/wildfly/standalone/deployments
