global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'keycloak'
    metrics_path: '/realms/master/metrics'
    static_configs:
      - targets: ['keycloak:8080']
  
  - job_name: 'keycloak2'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['keycloak:8080']
