global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'keycloak'
    metrics_path: '/realms/master/metrics'
    static_configs:
      - targets: ['keycloak:8080']
